@startuml sequence
hide footbox
skinparam style strictuml

actor User
participant "Compiler" as C
participant "TsSource" as TS
participant "Syntax" as SY
participant "Semantic" as SE
participant "CodeGenerator" as CG

User -> C : run(inputFile, outputFile)

C -> TS : new TsSource(inputFile)
C -> SY : new Syntax(TsSource)

C -> SY : parseProgram() （構文解析）
SY --> C : Program ast

C -> SE : new Semantic(ast) （意味解析）

C -> CG : new CodeGenerator()   
C -> CG : generate(ast)
CG --> C : casLines (List<String>)

C -> C : writeCas(casLines, outputFile)

C --> User : "OK"
@enduml
